swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
host: localhost:10010
basePath: /
paths:
  /testA/{id}/user:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
        default:
          description: '{"a": 5, "b": 10}'
  /testB:
    get:
      responses:
        "200":
          description: Success
  /swagger:
    x-swagger-pipe: swagger_raw
