swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
host: localhost:10010
basePath: /
paths:
  /testA/{id}/user:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
        default:
          description: '{"id": "abc", "description": "I am a good man", "type": "human being", "vod_type": "PIFF" }'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Success
        default:
          description: OK
  /testB:
    get:
      responses:
        "200":
          description: Success
